/* SkitStudio's visual identity, sampled from the app's own screens. */

export const C = {
  // canvas of the video
  ink: "#05060b",
  bg: "#090a13",
  bg2: "#0e0f1d",
  // app surfaces (editor, sheets, cards)
  app: "#0a0b14",
  panel: "#10111b",
  panel2: "#151726",
  card: "#1b1e2d",
  border: "#25283a",
  border2: "#30344a",
  // project list background (purple-tinted top)
  listTop: "#1d1742",
  listBottom: "#171a29",
  // accents
  purple: "#7c6cf8",
  purpleHi: "#9b8cff",
  purple2: "#966aff",
  purpleBtn: "#735dfe",
  purpleDeep: "#4b36d8",
  lavender: "#c9c2ff",
  cyan: "#22d3ee",
  cyanUi: "#00d8f8",
  pink: "#f472b6",
  green: "#22c55e",
  greenBar: "#3a8a40",
  blueBar: "#2896ef",
  red: "#f0606f",
  redBg: "#2a131c",
  // text
  text: "#f4f4fa",
  text2: "#aab0c4",
  muted: "#71778d",
  // the demo app (light theme)
  appBg: "#f7f7fc",
  appText: "#1c1a33",
  appMuted: "#8e8ca6",
  appField: "#ffffff",
  appBorder: "#d9d8ea",
  // code
  code: {
    bg: "#0b0c15",
    line: "#4a4f66",
    tag: "#8cc4ff",
    attr: "#9ad19f",
    value: "#f2a46f",
    punct: "#c9cbe0",
    comment: "#5f6780",
    keyword: "#c792ea",
    type: "#ffcb6b",
    fn: "#82aaff",
    plain: "#d8dbe8",
  },
};

export const F = {
  ui: "Roboto",
  display: "Sora",
  mono: "JetBrains Mono",
  icon: "Material Symbols Rounded",
};

/** Material Symbols Rounded codepoints (the app uses rounded outline icons). */
export const I = {
  add: "",
  edit: "",
  del: "",
  menu: "",
  save: "",
  play: "",
  grid: "",
  close: "",
  robot: "",
  code: "",
  expand: "",
  more: "",
  restore: "",
  person: "",
  store: "",
  video: "",
  folder: "",
  // palette
  linearV: "",
  linearH: "",
  frame: "",
  scroll: "",
  gradeIcon: "",
  radio: "",
  cardIcon: "",
  textView: "",
  editText: "",
  button: "",
  image: "",
  checkbox: "",
  switchIcon: "",
  progress: "",
  spinner: "",
  listView: "",
  gridView: "",
  // properties
  attrs: "",
  width: "",
  height: "",
  text: "",
  hint: "",
  font: "",
  touch: "",
  chevron: "",
  check: "",
  checkCircle: "",
  tree: "",
  bolt: "",
  download: "",
  phone: "",
  rocket: "",
  chat: "",
  wave: "",
  signal: "",
  wifi: "",
  battery: "",
  back: "",
  stop: "",
  circle: "",
};
